name: Build

on: [pull_request, workflow_dispatch]

jobs:
  packer:
    runs-on: self-hosted
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ./test/ubuntu-2004.json

      # Grab config file
      - name: config
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./test/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./test/ubuntu-2004.json

      # upload cloud-init

      - name: Upload configmap
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create configmap dir --from-file=./test/http

      - name: Upload Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./test/cloud-init.yaml

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort --var-file=./test/variables.json"
          target: ./test/ubuntu-2004.json

      # cleanup
      - name: Upload Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete -f ./test/cloud-init.yaml && kubectl delete cm dir