name: Build

on: [pull_request, workflow_dispatch]

jobs:
  config:
    runs-on: self-hosted
    steps:
      - run: echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./test/variables.json
  packer:
    runs-on: self-hosted
    needs: config
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ./test/ubuntu-2004.json

      # Grab config file
      - name: config
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./test/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./test/ubuntu-2004.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort --var-file=./test/variables.json"
          target: ./test/ubuntu-2004.json