name: Build

on: [pull_request, workflow_dispatch]

jobs:
  config:
    runs-on: self-hosted
    steps:
      - run: echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > variables.json
  check:
    runs-on: self-hosted
    needs: config
    steps:
      - run: ls -la
      - run: echo variables.json
  packer:
    runs-on: self-hosted
    needs: check
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ./test/ubuntu-2004.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./test/ubuntu-2004.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"

          target: ./test/ubuntu-2004.json