name: Build

on: [pull_request, workflow_dispatch]

jobs:
  packer:
    runs-on: self-hosted
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ./test/ubuntu-2004.json

      # Grab config file
      - name: Generate variables.json
        run : echo ${{ secrets.PACKER_CONFIG_BASE64 }} | base64 -d > ./test/variables.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./test/ubuntu-2004.json

      # Upload Configmap
      - name: Upload Configmap & Publish Cloud-Init Data
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: create configmap dir --from-file=./test/http && kubectl apply -f ./test/cloud-init.yaml

      # Upload cloud-init Data
     # - name: Upload Cloud-Init Data
     #   uses: steebchen/kubectl@master
     #   env:
     #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
     #   with:
     #     args: apply -f ./test/cloud-init.yaml

      # Replace HTTP reference
      - name: Replace HTTP reference
        uses: ubuntu-latest
        with:
          command: sed -i 's/{{ .HTTPIP }}:{{ .HTTPPort }}//cloudinit-service.virtualthoughts.co.uk/g' ./test/variables.json

      # Build Template
      - name: Build Template - Ubuntu 2004
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort --var-file=./test/variables.json -force"
          target: ./test/ubuntu-2004.json

      # cleanup
      - name: Delete Configmap & Remove Cloud-Init Data

        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: delete cm dir && kubectl delete -f ./test/cloud-init.yaml